// // cypress/support/locators.js

// export const locators = {
//   // --- Login ---
//   uname: "#uname",                   // Constants.uname
//   pass: "#pass",                     // Constants.pass
//   // submit: "#submit",
//   // verify: "#VerifyElement",

//   // --- Staff ---
//   SideIcon: "#sideIcon",
//   searchstaff: "#searchStaff",
//   Stafflist: "#stafflist",
//   Client: "#client",
//   ClientList: "#clientList",
//   addnewstaff: "#addNewStaff",
//   ASFname: "#ASFname",
//   ASLname: "#ASLname",
//   ASDOB: "#ASDOB",
//   credentials: "#credentials",
//   credentialsDD: "#credentialsDD",
//   ASclickout: "#ASClickOut",
//   ASrole: "#ASRole",
//   ASphnnumber: "#ASPhnNumber",
//   ASemailaddr: "#ASEmailAddr",
//   ASNewSLocation: "#ASNewSLocation",
//   ASselectlocation: "#ASSelectLocation",
//   ASselectlocationDD: "#ASSelectLocationDD",
//   ASgeneratecredentials: "#ASGenerateCredentials",
//   ASclose: "#ASClose",
//   ASstaffname: "#ASStaffName",
//   EditStaff: "#EditStaff",
//   ASschedule: "#ASSchedule",
//   ASaddavailability: "#ASAddAvailability",
//   ASaddavailability2: "#ASAddAvailability2",
//   ASdate: "#ASDate",
//   ASstarttime: "#ASStartTime",
//   ASendtime: "#ASEndTime",
//   ASaddnote: "#ASAddNote",
//   ASsave: "#ASSave",
//   DeactivateStaff: "#DeactivateStaff",
//   ConfirmDeactivateStaff: "#ConfirmDeactivateStaff",
//   ConfirmReactivateStaff: "#ConfirmReactivateStaff",
//   StaffUpdateManager: "#StaffUpdateManager",
//   SearchStaffManager: "#SearchStaffManager",
//   SelectStaffManager1: "#SelectStaffManager1",
//   SelectStaffManager2: "#SelectStaffManager2",
//   SubmitStaffManager: "#SubmitStaffManager",
//   selectstartingstaff: "#selectstartingstaff",
//   StaffSaveClick: "#StaffSaveClick",

//   // --- Child ---
//   Child_click: "#ChildClick",
//   ClientSearch: "#ClientSearch",
//   FirstListedClient1: "#FirstListedClient1",
//   ClientAction: "#ClientAction",
//   ClientEdit: "#ClientEdit",
//   Autoit_Upload: "#AutoitUpload",
//   Upload_Save_click: "#UploadSaveClick",
//   MRN: "#MRN",
//   MRNConfirm: "#MRNConfirm",
//   Client_id: "#ClientId",
//   FName: "#FName",
//   LName: "#LName",
//   ClientPronouns: "#ClientPronouns",
//   ClientPronounsDD: "#ClientPronounsDD",
//   ClientRace: "#ClientRace",
//   ClientRaceDD: "#ClientRaceDD",
//   PreferredName: "#PreferredName",
//   Email: "#Email",
//   Number: "#Number",
//   GenderClick: "#GenderClick",
//   GenderSelect: "#GenderSelect",
//   DobClick: "#DobClick",
//   Change_date: "#ChangeDate",
//   Select_date: "#SelectDate",
//   ConfirmDobClick: "#ConfirmDobClick",
//   ConfirmChange_date: "#ConfirmChangeDate",
//   ConfirmSelect_date: "#ConfirmSelectDate",
//   Staff_CFS: "#StaffCFS",
//   Select_CSF: "#SelectCSF",
//   Location: "#Location",
//   SelectLocation: "#SelectLocation",
//   Addressaddchild: "#AddressAddChild",
//   SelectAddressaddchild: "#SelectAddressAddChild",
//   Countryaddchild: "#CountryAddChild",
//   SelectCountryaddchild1: "#SelectCountryAddChild1",
//   SelectCountryaddchild: "#SelectCountryAddChild",
//   Stateaddchild: "#StateAddChild",
//   Stateaddchild1: "#StateAddChild1",
//   SelectStateaddchild: "#SelectStateAddChild",
//   Cityaddchild: "#CityAddChild",
//   Pincodeaddchild: "#PincodeAddChild",
//   Child_Save: "#ChildSave",
//   Child_Update: "#ChildUpdate",
//   Child_Update1: "#ChildUpdate1",
//   CPronoun: "#CPronoun",
//   CPronounDD: "#CPronounDD",
//   Checkaddchild: "#CheckAddChild",
//   ClientListAction: "#ClientListAction",
//   ClientTermminate: "#ClientTerminate",
//   ClientConfirmTermminate: "#ClientConfirmTerminate",
//   ClientTermminateDate: "#ClientTerminateDate",
//   ClientTermminateList: "#ClientTerminateList",
//   ClientActiveList: "#ClientActiveList",

//   // --- Funding Source ---
//   InsuranceDDclick: "#InsuranceDDClick",
//   InsuranceDDUpdate: "#InsuranceDDUpdate",
//   InsuranceDDClick1: "#InsuranceDDClick1",
//   InsuranceCheckbox: "#InsuranceCheckbox",
//   DDItem: "#DDItem",
//   FundSave: "#FundSave",
//   ClientInfo: "#ClientInfo",
//   CheckFundingSourcePage: "#CheckFundingSourcePage",
//   InsuranceFirstName: "#InsuranceFirstName",
//   InsuranceLastName: "#InsuranceLastName",
//   InsuranceAddress: "#InsuranceAddress",
//   InsuranceState: "#InsuranceState",
//   InsuranceStateDD: "#InsuranceStateDD",
//   InsuranceDOB: "#InsuranceDOB",
//   InsuranceConfirmDOB: "#InsuranceConfirmDOB",
//   InsuranceConfirmUpdate: "#InsuranceConfirmUpdate",
//   SearchCaseManager: "#SearchCaseManager",
//   ASFirstmanager: "#ASFirstmanager"
// }
